# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Matt/Projects/mipsfpga-display/new/mipsfpga-display.cache/wt [current_project]
set_property parent.project_path C:/Users/Matt/Projects/mipsfpga-display/new/mipsfpga-display.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files -quiet C:/Users/Matt/Projects/mipsfpga-display/new/mipsfpga-display.runs/cdc_fifo_gen_synth_1/cdc_fifo_gen.dcp
set_property used_in_implementation false [get_files C:/Users/Matt/Projects/mipsfpga-display/new/mipsfpga-display.runs/cdc_fifo_gen_synth_1/cdc_fifo_gen.dcp]
add_files -quiet C:/Users/Matt/Projects/mipsfpga-display/new/mipsfpga-display.runs/pal_bram_mem_gen_synth_1/pal_bram_mem_gen.dcp
set_property used_in_implementation false [get_files C:/Users/Matt/Projects/mipsfpga-display/new/mipsfpga-display.runs/pal_bram_mem_gen_synth_1/pal_bram_mem_gen.dcp]
add_files -quiet C:/Users/Matt/Projects/mipsfpga-display/new/mipsfpga-display.runs/fb_bram_mem_gen_synth_1/fb_bram_mem_gen.dcp
set_property used_in_implementation false [get_files C:/Users/Matt/Projects/mipsfpga-display/new/mipsfpga-display.runs/fb_bram_mem_gen_synth_1/fb_bram_mem_gen.dcp]
add_files -quiet C:/Users/Matt/Projects/mipsfpga-display/new/mipsfpga-display.runs/tb_hw_clk_wiz_synth_1/tb_hw_clk_wiz.dcp
set_property used_in_implementation false [get_files C:/Users/Matt/Projects/mipsfpga-display/new/mipsfpga-display.runs/tb_hw_clk_wiz_synth_1/tb_hw_clk_wiz.dcp]
read_verilog C:/Users/Matt/Projects/mipsfpga-display/new/mipsfpga-display.srcs/sources_1/imports/proj/include/mf_disp_conf.vh
read_verilog -library xil_defaultlib {
  C:/Users/Matt/Projects/mipsfpga-display/new/mipsfpga-display.srcs/sources_1/imports/proj/src/mf_disp_cmd_reg_top.v
  C:/Users/Matt/Projects/mipsfpga-display/new/mipsfpga-display.srcs/sources_1/imports/proj/src/mf_disp_intf_vga_top.v
  C:/Users/Matt/Projects/mipsfpga-display/new/mipsfpga-display.srcs/sources_1/imports/proj/src/mf_disp_fb_top.v
  C:/Users/Matt/Projects/mipsfpga-display/new/mipsfpga-display.srcs/sources_1/imports/proj/src/mf_disp_syncs.v
  C:/Users/Matt/Projects/mipsfpga-display/new/mipsfpga-display.srcs/sources_1/imports/proj/src/mf_disp_addr_dec.v
  C:/Users/Matt/Projects/mipsfpga-display/new/mipsfpga-display.srcs/sources_1/imports/proj/src/mf_disp_top.v
  C:/Users/Matt/Projects/mipsfpga-display/new/mipsfpga-display.srcs/sources_1/imports/proj/src/mf_disp_axi_top.v
  C:/Users/Matt/Projects/mipsfpga-display/new/mipsfpga-display.srcs/sources_1/imports/proj/src/mipsfpga_display.v
  C:/Users/Matt/Projects/mipsfpga-display/new/mipsfpga-display.srcs/sources_1/imports/sim/mf_disp_hw_axi_tb.v
}
read_xdc C:/Users/Matt/Projects/mipsfpga-display/new/mipsfpga-display.srcs/hw_tb_constrs/imports/hw_tb_constrs/mf_disp_hw_tb_pins.xdc
set_property used_in_implementation false [get_files C:/Users/Matt/Projects/mipsfpga-display/new/mipsfpga-display.srcs/hw_tb_constrs/imports/hw_tb_constrs/mf_disp_hw_tb_pins.xdc]

synth_design -top mf_disp_hw_axi_tb -part xc7a100tcsg324-1
write_checkpoint -noxdef mf_disp_hw_axi_tb.dcp
catch { report_utilization -file mf_disp_hw_axi_tb_utilization_synth.rpt -pb mf_disp_hw_axi_tb_utilization_synth.pb }
