# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/matt.lokes/Projects/mipsfpga-display/src/verilog/proj/ip/xil_2015_4/cdc_fifo_gen/cdc_fifo_gen.xci
# IP: The module: 'cdc_fifo_gen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/matt.lokes/Projects/mipsfpga-display/src/verilog/proj/ip/xil_2015_4/cdc_fifo_gen/cdc_fifo_gen/cdc_fifo_gen_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'cdc_fifo_gen'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/matt.lokes/Projects/mipsfpga-display/src/verilog/proj/ip/xil_2015_4/cdc_fifo_gen/cdc_fifo_gen/cdc_fifo_gen.xdc
# XDC: The top module name and the constraint reference have the same name: 'cdc_fifo_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/matt.lokes/Projects/mipsfpga-display/src/verilog/proj/ip/xil_2015_4/cdc_fifo_gen/cdc_fifo_gen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cdc_fifo_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Users/matt.lokes/Projects/mipsfpga-display/src/verilog/proj/ip/xil_2015_4/cdc_fifo_gen/cdc_fifo_gen.xci
# IP: The module: 'cdc_fifo_gen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/matt.lokes/Projects/mipsfpga-display/src/verilog/proj/ip/xil_2015_4/cdc_fifo_gen/cdc_fifo_gen/cdc_fifo_gen_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'cdc_fifo_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/matt.lokes/Projects/mipsfpga-display/src/verilog/proj/ip/xil_2015_4/cdc_fifo_gen/cdc_fifo_gen/cdc_fifo_gen.xdc
# XDC: The top module name and the constraint reference have the same name: 'cdc_fifo_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/matt.lokes/Projects/mipsfpga-display/src/verilog/proj/ip/xil_2015_4/cdc_fifo_gen/cdc_fifo_gen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cdc_fifo_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
