# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/matt.lokes/Projects/mipsfpga-display/new/mipsfpga-display.srcs/sources_1/ip/pal_bram_mem_gen/pal_bram_mem_gen.xci
# IP: The module: 'pal_bram_mem_gen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/matt.lokes/Projects/mipsfpga-display/new/mipsfpga-display.srcs/sources_1/ip/pal_bram_mem_gen/pal_bram_mem_gen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pal_bram_mem_gen'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Users/matt.lokes/Projects/mipsfpga-display/new/mipsfpga-display.srcs/sources_1/ip/pal_bram_mem_gen/pal_bram_mem_gen.xci
# IP: The module: 'pal_bram_mem_gen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/matt.lokes/Projects/mipsfpga-display/new/mipsfpga-display.srcs/sources_1/ip/pal_bram_mem_gen/pal_bram_mem_gen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pal_bram_mem_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
