# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/matt.lokes/Projects/mipsfpga-display/src/verilog/proj/ip/xil_2015_4/tb_hw_clk_wiz/tb_hw_clk_wiz.xci
# IP: The module: 'tb_hw_clk_wiz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/matt.lokes/Projects/mipsfpga-display/src/verilog/proj/ip/xil_2015_4/tb_hw_clk_wiz/tb_hw_clk_wiz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'tb_hw_clk_wiz'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/matt.lokes/Projects/mipsfpga-display/src/verilog/proj/ip/xil_2015_4/tb_hw_clk_wiz/tb_hw_clk_wiz.xdc
# XDC: The top module name and the constraint reference have the same name: 'tb_hw_clk_wiz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/matt.lokes/Projects/mipsfpga-display/src/verilog/proj/ip/xil_2015_4/tb_hw_clk_wiz/tb_hw_clk_wiz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tb_hw_clk_wiz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: C:/Users/matt.lokes/Projects/mipsfpga-display/src/verilog/proj/ip/xil_2015_4/tb_hw_clk_wiz/tb_hw_clk_wiz.xci
# IP: The module: 'tb_hw_clk_wiz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/matt.lokes/Projects/mipsfpga-display/src/verilog/proj/ip/xil_2015_4/tb_hw_clk_wiz/tb_hw_clk_wiz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'tb_hw_clk_wiz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/matt.lokes/Projects/mipsfpga-display/src/verilog/proj/ip/xil_2015_4/tb_hw_clk_wiz/tb_hw_clk_wiz.xdc
# XDC: The top module name and the constraint reference have the same name: 'tb_hw_clk_wiz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/matt.lokes/Projects/mipsfpga-display/src/verilog/proj/ip/xil_2015_4/tb_hw_clk_wiz/tb_hw_clk_wiz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tb_hw_clk_wiz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
