# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Matt/Projects/mipsfpga-display/src/verilog/vivado_proj/mf_disp_hw_tb_pins.xdc

# Block Designs: C:/Users/Matt/Projects/mipsfpga-display/src/verilog/bd/mf_disp_palette/mf_disp_palette.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mf_disp_palette || ORIG_REF_NAME==mf_disp_palette}]

# IP: C:/Users/Matt/Projects/mipsfpga-display/src/verilog/bd/mf_disp_palette/ip/mf_disp_palette_palette_blk_mem_gen_0/mf_disp_palette_palette_blk_mem_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mf_disp_palette_palette_blk_mem_gen_0 || ORIG_REF_NAME==mf_disp_palette_palette_blk_mem_gen_0}]

# Block Designs: C:/Users/Matt/Projects/mipsfpga-display/src/verilog/bd/mf_disp_fb/mf_disp_fb.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mf_disp_fb || ORIG_REF_NAME==mf_disp_fb}]

# IP: C:/Users/Matt/Projects/mipsfpga-display/src/verilog/bd/mf_disp_fb/ip/mf_disp_fb_framebuff_blk_mem_gen_0/mf_disp_fb_framebuff_blk_mem_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mf_disp_fb_framebuff_blk_mem_gen_0 || ORIG_REF_NAME==mf_disp_fb_framebuff_blk_mem_gen_0}]

# Block Designs: C:/Users/Matt/Projects/mipsfpga-display/src/verilog/bd/mf_disp_cdc_fifo/mf_disp_cdc_fifo.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mf_disp_cdc_fifo || ORIG_REF_NAME==mf_disp_cdc_fifo}]

# IP: C:/Users/Matt/Projects/mipsfpga-display/src/verilog/bd/mf_disp_cdc_fifo/ip/mf_disp_cdc_fifo_fifo_generator_0_0/mf_disp_cdc_fifo_fifo_generator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mf_disp_cdc_fifo_fifo_generator_0_0 || ORIG_REF_NAME==mf_disp_cdc_fifo_fifo_generator_0_0}]

# XDC: c:/Users/Matt/Projects/mipsfpga-display/src/verilog/bd/mf_disp_palette/ip/mf_disp_palette_palette_blk_mem_gen_0/mf_disp_palette_palette_blk_mem_gen_0_ooc.xdc

# XDC: C:/Users/Matt/Projects/mipsfpga-display/src/verilog/bd/mf_disp_palette/mf_disp_palette_ooc.xdc

# XDC: c:/Users/Matt/Projects/mipsfpga-display/src/verilog/bd/mf_disp_fb/ip/mf_disp_fb_framebuff_blk_mem_gen_0/mf_disp_fb_framebuff_blk_mem_gen_0_ooc.xdc

# XDC: C:/Users/Matt/Projects/mipsfpga-display/src/verilog/bd/mf_disp_fb/mf_disp_fb_ooc.xdc

# XDC: c:/Users/Matt/Projects/mipsfpga-display/src/verilog/bd/mf_disp_cdc_fifo/ip/mf_disp_cdc_fifo_fifo_generator_0_0/mf_disp_cdc_fifo_fifo_generator_0_0/mf_disp_cdc_fifo_fifo_generator_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mf_disp_cdc_fifo_fifo_generator_0_0 || ORIG_REF_NAME==mf_disp_cdc_fifo_fifo_generator_0_0}] {/U0 }]/U0 ]]

# XDC: c:/Users/Matt/Projects/mipsfpga-display/src/verilog/bd/mf_disp_cdc_fifo/ip/mf_disp_cdc_fifo_fifo_generator_0_0/mf_disp_cdc_fifo_fifo_generator_0_0/mf_disp_cdc_fifo_fifo_generator_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mf_disp_cdc_fifo_fifo_generator_0_0 || ORIG_REF_NAME==mf_disp_cdc_fifo_fifo_generator_0_0}] {/U0 }]/U0 ]]

# XDC: c:/Users/Matt/Projects/mipsfpga-display/src/verilog/bd/mf_disp_cdc_fifo/ip/mf_disp_cdc_fifo_fifo_generator_0_0/mf_disp_cdc_fifo_fifo_generator_0_0_ooc.xdc

# XDC: C:/Users/Matt/Projects/mipsfpga-display/src/verilog/bd/mf_disp_cdc_fifo/mf_disp_cdc_fifo_ooc.xdc
