# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000

create_project -in_memory -part xc7a100tcsg324-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Matt/Projects/mipsfpga-display/src/verilog/vivado_proj/mipsfpga_display.cache/wt [current_project]
set_property parent.project_path C:/Users/Matt/Projects/mipsfpga-display/src/verilog/vivado_proj/mipsfpga_display.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
set_property ip_repo_paths {
  C:/Users/Matt/Projects/mipsfpga-display/packaged_ip/mipsfpga_display_1.0
  C:/Users/Matt/ip_repo/mipsfpga_display_1.0
  C:/Users/Matt/ip_repo/mipsfpga-display_1.0
} [current_project]
read_verilog C:/Users/Matt/Projects/mipsfpga-display/src/verilog/src/mf_disp_conf.vh
add_files C:/Users/Matt/Projects/mipsfpga-display/src/verilog/bd/mf_disp_palette/mf_disp_palette.bd
set_property used_in_implementation false [get_files -all c:/Users/Matt/Projects/mipsfpga-display/src/verilog/bd/mf_disp_palette/ip/mf_disp_palette_palette_blk_mem_gen_0/mf_disp_palette_palette_blk_mem_gen_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/Matt/Projects/mipsfpga-display/src/verilog/bd/mf_disp_palette/mf_disp_palette_ooc.xdc]
set_property is_locked true [get_files C:/Users/Matt/Projects/mipsfpga-display/src/verilog/bd/mf_disp_palette/mf_disp_palette.bd]

add_files C:/Users/Matt/Projects/mipsfpga-display/src/verilog/bd/mf_disp_fb/mf_disp_fb.bd
set_property used_in_implementation false [get_files -all c:/Users/Matt/Projects/mipsfpga-display/src/verilog/bd/mf_disp_fb/ip/mf_disp_fb_framebuff_blk_mem_gen_0/mf_disp_fb_framebuff_blk_mem_gen_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/Matt/Projects/mipsfpga-display/src/verilog/bd/mf_disp_fb/mf_disp_fb_ooc.xdc]
set_property is_locked true [get_files C:/Users/Matt/Projects/mipsfpga-display/src/verilog/bd/mf_disp_fb/mf_disp_fb.bd]

add_files C:/Users/Matt/Projects/mipsfpga-display/src/verilog/bd/mf_disp_cdc_fifo/mf_disp_cdc_fifo.bd
set_property used_in_implementation false [get_files -all c:/Users/Matt/Projects/mipsfpga-display/src/verilog/bd/mf_disp_cdc_fifo/ip/mf_disp_cdc_fifo_fifo_generator_0_0/mf_disp_cdc_fifo_fifo_generator_0_0/mf_disp_cdc_fifo_fifo_generator_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Matt/Projects/mipsfpga-display/src/verilog/bd/mf_disp_cdc_fifo/ip/mf_disp_cdc_fifo_fifo_generator_0_0/mf_disp_cdc_fifo_fifo_generator_0_0/mf_disp_cdc_fifo_fifo_generator_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Matt/Projects/mipsfpga-display/src/verilog/bd/mf_disp_cdc_fifo/ip/mf_disp_cdc_fifo_fifo_generator_0_0/mf_disp_cdc_fifo_fifo_generator_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/Matt/Projects/mipsfpga-display/src/verilog/bd/mf_disp_cdc_fifo/mf_disp_cdc_fifo_ooc.xdc]
set_property is_locked true [get_files C:/Users/Matt/Projects/mipsfpga-display/src/verilog/bd/mf_disp_cdc_fifo/mf_disp_cdc_fifo.bd]

read_verilog -library xil_defaultlib {
  C:/Users/Matt/Projects/mipsfpga-display/src/verilog/src/mf_disp_syncs.v
  C:/Users/Matt/Projects/mipsfpga-display/src/verilog/src/mf_disp_intf_vga_top.v
  C:/Users/Matt/Projects/mipsfpga-display/src/verilog/src/mf_disp_fb_top.v
  C:/Users/Matt/Projects/mipsfpga-display/src/verilog/src/mf_disp_cmd_reg_top.v
  C:/Users/Matt/Projects/mipsfpga-display/src/verilog/src/mf_disp_addr_dec.v
  C:/Users/Matt/Projects/mipsfpga-display/src/verilog/src/mf_disp_top.v
  C:/users/matt/projects/mipsfpga-display/packaged_ip/mipsfpga_display_1.0/hdl/mipsfpga_display_v1_0_S00_AXI.v
  C:/users/matt/projects/mipsfpga-display/packaged_ip/mipsfpga_display_1.0/hdl/mipsfpga_display_v1_0.v
}
read_xdc C:/Users/Matt/Projects/mipsfpga-display/src/verilog/vivado_proj/mf_disp_hw_tb_pins.xdc
set_property used_in_implementation false [get_files C:/Users/Matt/Projects/mipsfpga-display/src/verilog/vivado_proj/mf_disp_hw_tb_pins.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
catch { write_hwdef -file mipsfpga_display_v1_0.hwdef }
synth_design -top mipsfpga_display_v1_0 -part xc7a100tcsg324-1
write_checkpoint -noxdef mipsfpga_display_v1_0.dcp
catch { report_utilization -file mipsfpga_display_v1_0_utilization_synth.rpt -pb mipsfpga_display_v1_0_utilization_synth.pb }
