# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/matt.lokes/Projects/mipsfpga-display/src/verilog/proj/mipsfpga_display_2015_4.cache/wt [current_project]
set_property parent.project_path C:/Users/matt.lokes/Projects/mipsfpga-display/src/verilog/proj/mipsfpga_display_2015_4.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files -quiet C:/Users/matt.lokes/Projects/mipsfpga-display/src/verilog/proj/mipsfpga_display_2015_4.runs/cdc_fifo_gen_synth_1/cdc_fifo_gen.dcp
set_property used_in_implementation false [get_files C:/Users/matt.lokes/Projects/mipsfpga-display/src/verilog/proj/mipsfpga_display_2015_4.runs/cdc_fifo_gen_synth_1/cdc_fifo_gen.dcp]
add_files -quiet C:/Users/matt.lokes/Projects/mipsfpga-display/src/verilog/proj/mipsfpga_display_2015_4.runs/pal_bram_mem_gen_synth_1/pal_bram_mem_gen.dcp
set_property used_in_implementation false [get_files C:/Users/matt.lokes/Projects/mipsfpga-display/src/verilog/proj/mipsfpga_display_2015_4.runs/pal_bram_mem_gen_synth_1/pal_bram_mem_gen.dcp]
add_files -quiet C:/Users/matt.lokes/Projects/mipsfpga-display/src/verilog/proj/mipsfpga_display_2015_4.runs/fb_bram_mem_gen_synth_1/fb_bram_mem_gen.dcp
set_property used_in_implementation false [get_files C:/Users/matt.lokes/Projects/mipsfpga-display/src/verilog/proj/mipsfpga_display_2015_4.runs/fb_bram_mem_gen_synth_1/fb_bram_mem_gen.dcp]
read_verilog C:/Users/matt.lokes/Projects/mipsfpga-display/src/verilog/proj/include/mf_disp_conf.vh
read_verilog -library xil_defaultlib {
  C:/Users/matt.lokes/Projects/mipsfpga-display/src/verilog/proj/src/mf_disp_sync.v
  C:/Users/matt.lokes/Projects/mipsfpga-display/src/verilog/proj/src/mf_disp_syncs.v
  C:/Users/matt.lokes/Projects/mipsfpga-display/src/verilog/proj/src/mf_disp_intf_vga_top.v
  C:/Users/matt.lokes/Projects/mipsfpga-display/src/verilog/proj/src/mf_disp_fb_top.v
  C:/Users/matt.lokes/Projects/mipsfpga-display/src/verilog/proj/src/mf_disp_cmd_reg_top.v
  C:/Users/matt.lokes/Projects/mipsfpga-display/src/verilog/proj/src/mf_disp_addr_dec.v
  C:/Users/matt.lokes/Projects/mipsfpga-display/src/verilog/proj/src/mf_disp_top.v
  C:/Users/matt.lokes/Projects/mipsfpga-display/src/verilog/proj/src/mf_disp_axi_top.v
  C:/Users/matt.lokes/Projects/mipsfpga-display/src/verilog/proj/src/mipsfpga_display.v
}
read_xdc C:/Users/matt.lokes/Projects/mipsfpga-display/src/verilog/proj/constrs/timing.xdc
set_property used_in_implementation false [get_files C:/Users/matt.lokes/Projects/mipsfpga-display/src/verilog/proj/constrs/timing.xdc]

synth_design -top mipsfpga_display -part xc7a100tcsg324-1
write_checkpoint -noxdef mipsfpga_display.dcp
catch { report_utilization -file mipsfpga_display_utilization_synth.rpt -pb mipsfpga_display_utilization_synth.pb }
